class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  resources :ts_sql_infos
  resources :ts_sql_infos
  resources :tjb_roles
  resources :tjb_role_authorities
  resources :tjb_resources
  resources :tjb_organizations
  resources :tjb_operators
  resources :tjb_operator_roles
  resources :tjb_nations
  resources :tjb_codes
  resources :tjb_authoritiy_resources
  resources :tjb_authorities
  resources :tjb_areas
  resources :ttr_trout_headers
  resources :ttr_trout_details
  resources :ttr_trin_headers
  resources :ttr_trin_details
  resources :ttr_request_headers
  resources :ttr_request_details
  resources :ttr_package_nos
  resources :ttr_package_headers
  resources :ttr_package_details
  resources :tsr_salereturnreq_payments
  resources :tsr_salereturnreq_headers
  resources :tsr_salereturnreq_details
  resources :tsr_salereturnreq_combins
  resources :tsr_salereturnreq_batches
  resources :tsr_salereturnin_headers
  resources :tsr_salereturnin_details
  resources :tsr_salereturnin_combins
  resources :tsr_salereturnin_batches
  resources :tsr_salereturn_logs
  resources :tsr_salereturn_labels
  resources :tsr_salereturn_attachments
  resources :tsr_refund_payments
  resources :tsr_refund_headers
  resources :tsr_refund_details
  resources :tso_saleorder_states
  resources :tso_saleorder_receivers
  resources :tso_saleorder_payments
  resources :tso_saleorder_logs
  resources :tso_saleorder_labels
  resources :tso_saleorder_invoices
  resources :tso_saleorder_headers
  resources :tso_saleorder_gifts
  resources :tso_saleorder_details
  resources :tso_saleorder_deliveries
  resources :tso_saleorder_combinproducts
  resources :tso_saleorder_audits
  resources :tso_delivery_print_logs
  resources :tso_delivery_headers
  resources :tso_delivery_expresschases
  resources :tso_delivery_details
  resources :tso_delivery_combinproducts
  resources :tso_delivery_batches
  resources :ts_sys_store_logs
  resources :ts_sys_parameters
  resources :ts_saleorder_types
  resources :ts_saleorder_marks
  resources :ts_saleorder_mark_sets
  resources :ts_codes
  resources :tps_mult_inventory_warehouses
  resources :tps_mult_inventory_warehouse_details
  resources :tps_mult_inventory_headers
  resources :tps_mult_inventory_details
  resources :tps_inventory_headers
  resources :tps_inventory_details
  resources :tps_adjust_headers
  resources :tps_adjust_details
  resources :tpos_sale_headers
  resources :tpos_sale_details
  resources :tpos_pay_types
  resources :tpos_customers
  resources :tpos_customer_levels
  resources :tpo_rtv_receivers
  resources :tpo_rtv_headers
  resources :tpo_rtv_details
  resources :tpo_rm_headers
  resources :tpo_rm_details
  resources :tpo_prerm_headers
  resources :tpo_prerm_details
  resources :tpo_pre_replenishes
  resources :tpo_contract_headers
  resources :tpo_contract_details
  resources :tpo_apply_headers
  resources :tpo_apply_details
  resources :tout_products
  resources :tout_product_albums
  resources :tout_areas
  resources :top_operator_warehouses
  resources :top_operator_suppliers
  resources :top_operator_stores
  resources :tbw_warehouses
  resources :tbw_warehouse_logs
  resources :tbw_tandh_records
  resources :tbw_stores
  resources :tbw_store_parameters
  resources :tbw_store_exts
  resources :tbw_store_accounts
  resources :tbw_locations
  resources :tbw_bins
  resources :tbw_bin_types
  resources :tbs_suppliers
  resources :tbs_supplier_warehouses
  resources :tbs_supplier_stores
  resources :tbs_first_suppliers
  resources :tbp_store_products
  resources :tbp_promotion_stores
  resources :tbp_promotion_product_scopes
  resources :tbp_promotion_outproducts
  resources :tbp_promotion_inproducts
  resources :tbp_promotion_headers
  resources :tbp_promotion_gifts
  resources :tbp_products
  resources :tbp_product_warehouses
  resources :tbp_product_types
  resources :tbp_product_suppliers
  resources :tbp_product_skus
  resources :tbp_product_minmaxes
  resources :tbp_product_mappings
  resources :tbp_product_logs
  resources :tbp_product_locations
  resources :tbp_product_exts
  resources :tbp_product_costs
  resources :tbp_product_blacklists
  resources :tbp_product_barcodes
  resources :tbp_package_units
  resources :tbp_first_products
  resources :tbp_curing_headers
  resources :tbp_curing_details
  resources :tbp_combin_headers
  resources :tbp_combin_details
  resources :tbp_cmedicine_buckets
  resources :tbp_brands
  resources :tbp_barcode_print_logs
  resources :tbe_expresses
  resources :tbe_express_print_templates
  resources :tbe_express_platforms
  resources :tbe_express_onlineatts
  resources :tbe_express_onlineattr_warehouses
  resources :tbe_express_areas
  resources :tbc_files
  resources :tbc_companies
  resources :tbc_certificate_imgs
  resources :tout_products
  resources :tout_product_types
  resources :tout_product_albums
  resources :tout_brands
  resources :tout_areas
  resources :tout_products
  resources :tout_product_types
  resources :tout_product_albums
  resources :tout_brands
  resources :tout_areas
  draw :route_common
end
